package service

import (
	"strings"
	"testing"
)

func TestShellQuoteEnvValue_Basic(t *testing.T) {
	got, err := shellQuoteEnvValue("/Users/foo")
	if err != nil {
		t.Fatalf("err: %v", err)
	}
	if got != `'/Users/foo'` {
		t.Errorf("got %q", got)
	}
}

func TestShellQuoteEnvValue_Empty(t *testing.T) {
	got, err := shellQuoteEnvValue("")
	if err != nil || got != "''" {
		t.Errorf("got %q err %v", got, err)
	}
}

func TestShellQuoteEnvValue_SingleQuote(t *testing.T) {
	got, err := shellQuoteEnvValue(`foo's`)
	if err != nil {
		t.Fatalf("err: %v", err)
	}
	// close + escaped + reopen pattern
	if got != `'foo'\''s'` {
		t.Errorf("got %q", got)
	}
}

func TestShellQuoteEnvValue_Backslash(t *testing.T) {
	// Single-quoted strings pass through backslashes literally — no escaping needed.
	got, err := shellQuoteEnvValue(`C:\path`)
	if err != nil {
		t.Fatalf("err: %v", err)
	}
	if got != `'C:\path'` {
		t.Errorf("got %q", got)
	}
}

func TestShellQuoteEnvValue_Newline(t *testing.T) {
	if _, err := shellQuoteEnvValue("foo\nbar"); err == nil {
		t.Error("expected error on newline")
	}
	if _, err := shellQuoteEnvValue("foo\rbar"); err == nil {
		t.Error("expected error on CR")
	}
}

func TestRenderEnvFile_Deterministic(t *testing.T) {
	// Keys in input map intentionally unsorted; output must be stable (sorted).
	env := map[string]string{
		"OCTO_DAEMON_UNDER_SERVICE": "1",
		"HOME":                      "/Users/caster",
		"PATH":                      "/opt/homebrew/bin:/usr/bin",
	}
	out, err := RenderEnvFile(env)
	if err != nil {
		t.Fatalf("err: %v", err)
	}
	want := "# Generated by octo-daemon service install. Do not edit manually.\n" +
		"export HOME='/Users/caster'\n" +
		"export OCTO_DAEMON_UNDER_SERVICE='1'\n" +
		"export PATH='/opt/homebrew/bin:/usr/bin'\n"
	if out != want {
		t.Errorf("mismatch\ngot:\n%s\nwant:\n%s", out, want)
	}
}

func TestRenderEnvFile_PropagatesQuoteError(t *testing.T) {
	_, err := RenderEnvFile(map[string]string{"BAD": "line1\nline2"})
	if err == nil {
		t.Error("expected error from embedded newline")
	}
}

func TestWrapperScriptContent_ExecAndNoExitMapping(t *testing.T) {
	s := WrapperScriptContent()
	if !strings.Contains(s, `exec "$@"`) {
		t.Errorf("wrapper must exec; got:\n%s", s)
	}
	// Safety: regressions to capturing-exit-code should fail this test loudly.
	// The wrapper must NOT contain `$?` or `case` — exit-code mapping happens in Go main.
	if strings.Contains(s, "$?") || strings.Contains(s, "case ") {
		t.Errorf("wrapper must not capture exit code; got:\n%s", s)
	}
}
