package service

import (
	"fmt"
	"sort"
	"strings"
)

// wrapperScript is the shell wrapper that sources the env file then execs the
// daemon. Exec-only by design — service managers must see the daemon PID
// directly; exit-code mapping happens in main.go (plan §二.2.2).
const wrapperScript = `#!/bin/sh
set -u
env_file="$1"
shift
if [ -f "$env_file" ]; then
  . "$env_file"
fi
exec "$@"
`

// WrapperScriptContent returns the wrapper body. Stable output for golden tests.
func WrapperScriptContent() string { return wrapperScript }

// RenderEnvFile renders an env file in shell source format.
// All keys are written with `export KEY='value'` quoting (single-quote wrapped).
// Values containing newlines / CR return an error — env values should never
// contain those, and silently smuggling them in would break wrapper's `.` load.
func RenderEnvFile(env map[string]string) (string, error) {
	keys := make([]string, 0, len(env))
	for k := range env {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	var b strings.Builder
	b.WriteString("# Generated by octo-daemon service install. Do not edit manually.\n")
	for _, k := range keys {
		quoted, err := shellQuoteEnvValue(env[k])
		if err != nil {
			return "", fmt.Errorf("env[%s]: %w", k, err)
		}
		fmt.Fprintf(&b, "export %s=%s\n", k, quoted)
	}
	return b.String(), nil
}

// shellQuoteEnvValue wraps a value in POSIX single quotes, escaping embedded
// single quotes as '\''. Rejects newlines / CR.
func shellQuoteEnvValue(v string) (string, error) {
	if strings.ContainsAny(v, "\n\r") {
		return "", fmt.Errorf("env value contains newline or carriage return")
	}
	// close-quote + escaped-single-quote + reopen-quote pattern.
	return "'" + strings.ReplaceAll(v, "'", `'\''`) + "'", nil
}
